### PR TITLE
chore: update katex to 0.12.0

### PR DESCRIPTION
**Pull request by michaelmyc**
Updating to latest packages. Katex 0.11.1 and 0.12.0 seems to use different CSS class names, so these changes aren't backward compatible. 

Referencing issue #1

### CODE REVIEW

**Comment by michaelmyc** [comment]
We would also need to update the demo page.

**Comment by michaelmyc** [comment]
Bump! @Puritanic

**Comment by darktasevski** [comment]
Sorry, I've somehow missed GH notification. I'll go through PR ASAP.

**Comment by darktasevski** [comment]
@6etacat Any particular reason why you've bumped versions of almost everything in package.json? :) Not that I'm against it, just wondering why. 

Other than that everything looks fine, thank you for these changes!

**Comment by michaelmyc** [comment]
No particular reason except that I like stuff to be up to date. I have no evidence, but I guess being up to date makes it more likely to have better performance and less likely to be exposed to vulnerabilities. We can ignore everything except katex if there is a reason to do so.

**Review by darktasevski — APPROVED** [review]
LGTM 👍

**Pull request merged**
